### ISSUE TITLE
Error: AttributeError: module 'cv2' has no attribute 'dnn'

### ISSUE THREAD

**Issue by nullbyte91** [arunponnusamy/object-detection-opencv#1]
When I execute the below command on Python openCV virtual environment, I am getting an error.

$ python yolo_opencv.py --image dog.jpg --config yolov3.cfg --weights yolov3.weights --classes yolov3.txt

Error Logs:
Traceback (most recent call last):
  File "yolo_opencv.py", line 59, in <module>
    net = cv2.dnn.readNet(args.weights, args.config)
AttributeError: module 'cv2' has no attribute 'dnn'

**Comment by arunponnusamy** [comment]
Hello @nullbyte91, 

May I know how did you install OpenCV Python bindings ? Did you compile it from source from the OpenCV master branch ?

**Comment by nullbyte91** [comment]
Yes. deep neural network available from OpenCV 3.3 V. So, I could able to this with the latest version.

**Comment by muskanpriya15** [comment]
When I run my program I got this error(AttributeError: module 'cv2' has no attribute 'Dnn'). My opencv version is 4.5.4 still I got error.

**Comment by idrismerdefi** [comment]
i have same issues
