### ISSUE TITLE
readNet issue

### ISSUE THREAD

**Issue by ca1941** [arunponnusamy/object-detection-opencv#2]
net = cv2.dnn.readNet(args.weights, args.config)
AttributeError: module 'cv2.dnn' has no attribute 'readNet'

**Comment by arunponnusamy** [comment]
Hello @ca1941 ,
May I know how did you install OpenCV Python bindings ? Did you compile it from source from opencv master branch ?

**Comment by shrybht** [comment]
net = cv2.dnn.readNet(args.weights, args.config)
cv2.error: OpenCV(3.4.2) C:\projects\opencv-python\opencv\modules\dnn\src\darknet\darknet_io.cpp:684: error: (-215:Assertion failed) ifile.is_open() in function 'cv::dnn::darknet::ReadDarknetFromWeightsFile'

I couldn't understand the error, could you please help me fix this?

**Comment by arunponnusamy** [comment]
I am closing this issue. Feel free to reopen if the issue persists.

**Comment by bebe04** [comment]
hey! i have the same problem. I've install opencv with `pip install numpy opencv-python`
