### ISSUE TITLE
cv2.dnn.readNet issue with Tiny cfg

### ISSUE THREAD

**Issue by limkimhoe** [arunponnusamy/object-detection-opencv#3]
Hi 

Thanks for your sharing. 

I have no issue with the yolov3 weights and yolov3.cfg but I got the following issue with Yolov3_tiny.weights and Yolov3_tiny.cfg.

cv2.error: OpenCV(3.4.3) /Users/travis/build/skvark/opencv-python/opencv/modules/dnn/src/darknet/darknet_io.cpp:507: error: (-215:Assertion failed) separator_index < line.size() in function 'ReadDarknetFromCfgStream'

Just wonder if you have any idea?

**Comment by arunponnusamy** [comment]
Hello @limkimhoe , I have not tried tiny YOLO yet. It's on my to-do list to try next. I will give it a try and get back to you.

**Comment by limkimhoe** [comment]
Thank you in advance!

**Comment by limkimhoe** [comment]
Sorry, just tried. I think it got no problem, my issue was the number anchors. I got 9 pairs and the number was stated 6.

**Comment by limkimhoe** [comment]
Hi Arun,

I found something interesting.

https://stackoverflow.com/questions/36921249/drawing-angled-rectangles-in-opencv

Wonder if this applicable to OpenCV with YOLO weight.

**Comment by arunponnusamy** [comment]
Hello @limkimhoe , I am not sure I understood your question clearly. You want to draw angled rectangles over detected objects using YOLO in the image?

**Comment by limkimhoe** [comment]
Yes, happened that I came across that post and I find it interesting to share.

**Comment by MURL1DHAR** [comment]
@limkimhoe I came across the same issue you had earlier. Can you please tell, how can I know number of anchors I have? I have put 3 but I am not sure. I am following this tutorial and they dont explain on how to count anchors : http://emaraic.com/blog/yolov3-custom-object-detector#ref1

**Comment by limkimhoe** [comment]
> @limkimhoe I came across the same issue you had earlier. Can you please tell, how can I know number of anchors I have? I have put 3 but I am not sure. I am following this tutorial and they dont explain on how to count anchors : http://emaraic.com/blog/yolov3-custom-object-detector#ref1

@MURL1DHAR You can run the following script to check the anchors of your images for better result. Example for 480x480 9 pairs of anchors:
darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 480 -heigh 480

Anchors looks like:
37.5147,61.6030, 45.9996,87.0276, 55.9612,106.0157, 69.6980,128.4734, 87.5660,154.2261, 63.9268,244.7612, 94.8347,186.5155, 100.9767,341.4545, 139.2702,283.6874

After each pair, there is a space gap. 

So your Yolo layer in cfg file will state num=9. The Tiny model, cfg given 6 anchors. So you have to recalculate your images with 6 anchors.

Hope it is clear and able to helps.
