### ISSUE TITLE
IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by SXHRYU** [arunponnusamy/object-detection-opencv#34]
I've done everything that is required in README, but once I put `python yolo_opencv.py --image dog.jpg --config yolov3.cfg --weights yolov3.weights --classes yolov3.txt` in Terminal I get the following error:

`Traceback (most recent call last):
  File "C:\Users\.....\yolo_opencv.py", line 50, in <module>
    outs = net.forward(get_output_layers(net))
  File "C:\Users\......\yolo_opencv.py", line 20, in get_output_layers
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  File "C:\.....\yolo_opencv.py", line 20, in <listcomp>
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable.`

I've tried experimenting with `i[0] - 1` (like putting `i[0]` or `i[1] - 1`) but to no avail. Am I doing something wrong? Can someone help, pretty please? 
(I'm using PYCharm latest version (as of 04.11), just in case)
Thank you in advance!

**Comment by arunponnusamy** [comment]
Can you try changing I[0] - 1 to i - 1 ?

**Comment by SXHRYU** [comment]
Thanks, it worked!
I also changed 
`for i in indices:
    i = i[0]`
line by removing `i = i[0]`

**Comment by EmperoroftheMultiverse** [comment]
in Line 28
instead of writing output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
write output_layers = [layer_names[i - 1] for i in net.getUnconnectedOutLayers()]

in Line 92
delete i = i[0]
