### ISSUE TITLE
How can I do when 'IndexError: invalid index to scalar variable'. Its different from #34

### ISSUE THREAD

**Issue by Arannnn** [arunponnusamy/object-detection-opencv#35]
`D:\...\YOLOobject-detection-opencv>python yolo_opencv.py --image dog.jpg --config yolov3.cfg --weights yolov3.weights --classes yolov3.txt
Traceback (most recent call last):
  File "D:\...\YOLOobject-detection-opencv\yolo_opencv.py", line 63, in <module>
    outs = net.forward(get_output_layers(net))
  File "D:\...\YOLOobject-detection-opencv\yolo_opencv.py", line 28, in get_output_layers
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  File "D:\...\YOLOobject-detection-opencv\yolo_opencv.py", line 28, in <listcomp>
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable.`

**Comment by Arannnn** [comment]
sorry. my English its terrible.i thought i will solve this problem independently
this problem may be same to #34

**Comment by arunponnusamy** [comment]
Can you check with older version of OpenCV (4.5.3.56 or lower) ?

**Comment by Arannnn** [comment]
Thank you for your help,i solved this problem with the method proposed by #34.
