### ISSUE TITLE
TypeError: integer argument expected, got float

### ISSUE THREAD

**Issue by farzadhallaji** [arunponnusamy/object-detection-opencv#6]
I get this error 
```
python yolo_opencv.py --image dog.jpg --config yolov3.cfg --weights yolov3.
weights --classes yolov3.txt
Traceback (most recent call last):
  File "yolo_opencv.py", line 93, in <module>
    draw_prediction(image, class_ids[i], confidences[i], round(x), round(y), round(x+w), round(y+h))
  File "yolo_opencv.py", line 36, in draw_prediction
    cv2.rectangle(img, (x,y), (x_plus_w,y_plus_h), color, 2)
TypeError: integer argument expected, got float
```
so I changed this line

`98    draw_prediction(image, class_ids[i], confidences[i], round(x), round(y), round(x+w), round(y+h))`
to 
`    draw_prediction(image, class_ids[i], confidences[i], int(x), int(y), int(x+w), int(y+h))
`
and then it solved

**Comment by arunponnusamy** [comment]
Thanks for sharing the details @farzadhallaji .
May I know the Python and OpenCV version you are working with ?

**Comment by farzadhallaji** [comment]
Sure,
Python 2.7.12
OpenCV 3.4.3

**Comment by arunponnusamy** [comment]
Can you give it a try with Python 3 ?

**Comment by shaarkrat2** [comment]
with python3, you don't have the error is you keep 
`draw_prediction(image, class_ids[i], confidences[i], round(x), round(y), round(x+w), round(y+h)`
