### ISSUE TITLE
Training the model

### ISSUE THREAD

**Issue by shrybht** [arunponnusamy/object-detection-opencv#9]
Hi @arunponnusamy ,

I might not make sense, so I apologize beforehand. I understand that the DNN module provided here is just for running the images. But in case I want to train the model and check the outcome myself. Or to put it in a better way; what if I would want to make changes to the existing YOLO model to either improve the results. How do I approach? Could you please suggest on how to go about?

**Comment by arunponnusamy** [comment]
Hello @shrybht , you can learn more here http://preddie.com/darknet/yolo/
